class ViewMenu:
    def mostrar_menu(self):
        print("\n1. Cadastrar Cliente")
        print("2. Mostrar Cliente")
        print("3. Remover Cliente")
        print("4. Agendar Consulta")
        print("5. Mostrar Consultas")
        print("6. Remover Consulta")
        print("7. Cadastrar Médico")
        print("8. Mostrar Médico")
        print("9. Remover Médico")
        print("10. Cadastrar Atendente")
        print("11. Mostrar Atendente")
        print("12. Remover Atendente")
        print("13. Gerar Relatório de Consultas")
        print("14. Gerar Relatório de Clientes")
        print("0. Sair")
