class ViewMenuAdministrador:
    def mostrar_menu(self):
        print("1. Criar Cliente")
        print("2. Editar Cliente")
        print("3. Remover Cliente")
        print("4. Criar Médico")
        print("5. Editar Médico")
        print("6. Remover Médico")
        print("7. Criar Atendente")
        print("8. Editar Atendente")
        print("9. Remover Atendente")
        print("10. Criar Administrador")
        print("11. Editar Administrador")
        print("12. Remover Administrador")
        print("0. Sair")
